sudo: false
language: php

dist: trusty

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION='^3.4'
    - php: 7.1
      env: SYMFONY_VERSION='^4.0'
    - php: 7.2
      env: SYMFONY_VERSION='^3.4'
    - php: 7.2
      env: SYMFONY_VERSION='^4.0'

  fast_finish: true

before_script:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/framework-bundle:${SYMFONY_VERSION}"; fi;
    - composer install
    - mkdir -p build/logs

script: ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - composer require satooshi/php-coveralls
  - ./vendor/bin/coveralls -v

cache:
    directories:
        - $HOME/.composer/cache
